### ISSUE TITLE
Not importing the correct path (and path separator symbol)

### ISSUE THREAD

**Issue by ErickXavier** [maxi7587/angular-auto-import#1]
Hi,

I just installed the package and on my first try it didn't work kinda well.
I opened my new component and typed the constructor inject content when it automaticaly included the code on the second line of this code. As you can see it tried to use the symbol '\\' instead of the '/'. Other thing it done was to try to use an absolute path when a relative would have been the best choice, since the file is in a directory right before the current path (../services.service) and belongs to the component I'm building.

And even when I change the \ to / the path is wrong and the service is not imported correctly.

Check the screenshot bellow to see what happened:
![image](https://user-images.githubusercontent.com/648239/39398083-01e68218-4adf-11e8-93ba-96acddc96290.png)

Besides that, keep the awesome work. The detection and inclusion of the code was really fast. Congrats on that ;)

I'm using Windows 10 with Atom v1.26.0 x64 (all packages updated).

**Comment by maxi7587** [comment]
Thanks for the info! I'm using Linux and haven't experienced the issue... I've been a little busy recently but  but will try to fix it as soon as I can. There are also other errors and improves to make... maybe it would be better to emphasize in the most important feature at first. If not this will end in an eternal beta XD.

If you want to contribute with a few lines of code you're invited to make a fork. Thanks again and hope to fix this in the next days!

**Comment by maxi7587** [comment]
Hi again @ErickXavier !

I have released a new path version today trying to resolve the issue about backslashes. I don't have Windows installed and will test it tomorrow in a VM, but if you cant update and test if the import statement has the correct slashes it would be great.

In the next release I'll add a method to generate the imports using relative paths (added enhancement tag). Thanks for the advise!

**Comment by ErickXavier** [comment]
> Hi again @ErickXavier !
> 
> I have released a new path version today trying to resolve the issue about backslashes. I don't have Windows installed and will test it tomorrow in a VM, but if you cant update and test if the import statement has the correct slashes it would be great.
> 
> In the next release I'll add a method to generate the imports using relative paths (added enhancement tag). Thanks for the advise!

Hi @maxi7587, I'm so sorry I didn't see your answer before. I've being working hard on my company's projects.

Anyways, I'm trying to test here, but the shortcut itself (ctrl-alt-i) doesn't work, even the custom one I configured is not working (ctrl-i). Then I tried using the ctrl-shit-p menu and still not working. It simply does nothing. Any idea how to fix it? Anyway I can help you debug this issue?
